### ISSUE TITLE
최근 공부하는 알고리즘 & 대기업 코딩테스트 경향 정리

### ISSUE THREAD

**Issue by ggjae** [Seogeurim/CS-study#26]
[알고리즘 공부 어떻게 시작할까요?](https://baactree.tistory.com/52)
[기초부터 고급까지 알고리즘](https://baactree.tistory.com/14)

최근 소마 코테에서 union-find와 bfs 응용, 분할 정복을 마주하여 떠오르는 아이디어가 없어 시험 시간 내내 골치 아팠습니다. 다시 시작하는 마음으로 코딩테스트에서 자주 출제되는 부분들을 정리해봤어요.

BFS의 끝판왕 : https://www.acmicpc.net/problem/3197 자 드가자

배열 문자열 bruteforce 재귀 백트래킹 동적계획법 BFS/DFS는 기본입니다.

카카오) 프로그래머스 Lv 3,4
효율성테스트 문제가 존재, REST API통신 코드관련 문제

2019- 문자열, 재귀함수, 2차배열, 트라이 자료구조 or 이분탐색보다 효율적 방법찾기
구현, 완전탐색 bitmask, 수열, BFS

2018 - 해시, 배열, 정렬, DFS, bit, 이진트리, 정규표현식

우아한형제들) 원형 자료구조, 라인스위핑, 직사각형 면적문제

라인) 자료구조, 정렬, 문자열, 해시맵, 트리, 링크드리스트, BFS, 이분탐색, 완전탐색

삼성) BFS, DFS, 동적계획법, 재귀함수, 경우의수(순열과 조합), 시뮬레이션

참조- 잠들기 전에 보면 좋은 알고리즘에 관한 youtube

**Comment by Seogeurim** [comment]
와... 안 그래도 코딩테스트로는 이러이러한 유형이 나오는 것 같다 하고 막연하게만 생각하고 있었는데, 이렇게 정리해주시니 너무 좋은 참고 자료가 될 것 같습니다 ㅠㅠ!!! 감사합니다 맨날 들어와서 볼게요 😆 !!

**Comment by Hee-Jae** [comment]
삼성 기출만 보면서 시뮬레이션, 완전탐색만 주로 했었는데 기업들 마다 주로 출제되는 알고리즘이 다 다르군요. 이제부터는 편식안하고 다양하게 공부 해야겠어요ㅎㅎ 좋은 자료 감사합니다!

**Comment by ggjae** [comment]
@Seogeurim 그림씨가 가고싶어하는 네이버는 '자료구조'를 정말 중시합니다. 기대할게요!
@Hee-Jae 저는 그리디만 할 줄 알면 다 되는 줄 알았어요. ㅋㅋ 그리디만 풀어왔는데 휴..

**Comment by Seogeurim** [comment]
@ggjae NAVER.... NEVER can go......
