### ISSUE TITLE
[알고리즘] DFS 구현 코드에서 궁금한 점

### ISSUE THREAD

**Issue by ggjae** [Seogeurim/CS-study#72]
알고리즘을 다시 보게 되면서 @KimKwon 혁진님이 작성하신 DFS, BFS.md 파일에서 궁금한 것이 생겼습니다.

```
void dfs(int current) {
    if (current == target) { // 목적지인가?
        System.out.println("목적지입니다.");
        return;
    }
    visited[current] = true; // 체크인
    for (int next : graph[current]) { // 갈 수 있는 곳을 순회
        if (!visited[next]) { // 갈 수 있는가?
            dfs(next); // 간다
        }
    }
    visited[current] = false; // 체크아웃
}
```

마지막 줄에 체크아웃이 의미하는 것은 뭔가요? 제 기억에 DFS는 모두 false로 시작하여, 방문한 곳은 true로 만들어주는것이 일반적인 것 아닌가요? 사이클을 검사하기 위하여 false를 사용한것인지....

**Comment by KimKwon** [comment]
이건 제가 작성한 코드가 아닙니다 @Seogeurim 님이 작성하신 문서에용

**Comment by ggjae** [comment]
아, 작성자가 혁진님으로 되어 있어서 오해했네요!

백트래킹은 유망노드를 판별하고, 유망하다면 keep going 하지 않다면 돌아간다. 라고 이해하고 있었는데 이 때 checkout과 비슷한 개념이군요? dfs와 백트래킹에 대한 차이점은 뭘까요? 단순히 dfs라면 'search'의 목적이 큰 것이라고 생각하는데 체크아웃이 필요한것인지 잘 모르겠습니다.

**Comment by Hee-Jae** [comment]
@ggjae 제 생각에도 단순히 `current`에서 `target`으로 갈 수 있는 경로가 있는지 파악할 때는 굳이 체크아웃이 필요하지 않습니다.

다만 다음과 같은 상황에서는 체크아웃이 필요합니다.
경로가 아래와 같이 설정되어 있고 길을 **두 번만** 건너서 목적지에 도달 해야한다고 가정해봅시다.

<img src="https://user-images.githubusercontent.com/22339356/132866749-ede7cc8d-cd1f-457c-8d9f-b2027b0de9da.png" width="250"/>

DFS를하면 아래 순서로 탐색 할겁니다.
1 -> 2 -> 3
1 -> 2 -> 4
1 -> 3 -> 2
1 -> 3 -> 5 (도착)

이때 만약에 백트래킹을 하는 과정에서 체크아웃을 해주지 않는다면 1 -> 3 -> 2 과정이 진행되지 않을 것입니다.
2번 노드와 3번 노드가 이미 방문처리 되었기 때문이죠.
이렇게 이미 한 번의 경로 탐색에서 방문했던 노드를 새로운 경로로 다시 탐색하고자 할 때 체크아웃이 필요합니다.

**Comment by Seogeurim** [comment]
dfs 알고리즘을 "완전탐색" 알고리즘으로 사용했을 경우 체크아웃이 필요합니다. 위에서 희재님이 잘 설명해주신 것처럼 모든 경로를 탐색하기 위해서는 체크아웃을 진행해야 합니다.

dfs와 백트래킹의 차이점은, dfs를 통해 갈 수 있는 모든 경로를 탐색하던 중 굳이 가보지 않아도 되는(정답이 절대 될 수 없는 조건의) 경로를 찾았을 경우 탐색을 중단(가지치기)하고 다음 경로를 탐색하는 것을 말합니다. 백트래킹 때문에 체크아웃을 하는 개념이 아닌, 모든 경로를 완전탐색하기 위해 체크아웃을 해야 합니다.

**Comment by ggjae** [comment]
이해되었습니다! 감사합니다 :)
